"""
pdf_generator.py - WorkVision branded PDF generation utilities.
Uses fpdf2 to produce PDFs with:
  - WorkVision logo at top-left on every page header
  - Semi-transparent logo watermark centred on every page
  - Clean, professional layout
"""

from fpdf import FPDF, XPos, YPos
import os
import datetime

# -- Paths -------------------------------------------------------------------
import io
import matplotlib.pyplot as plt

# Use 'Agg' backend so matplotlib doesn't try to open GUI windows
plt.switch_backend('Agg')

BACKEND_DIR = os.path.dirname(os.path.abspath(__file__))
LOGO_PATH   = os.path.join(BACKEND_DIR, "static", "logo.png")
LOGO_FAINT_PATH = os.path.join(BACKEND_DIR, "static", "logo_faint.png")

# -- Brand Colours (RGB) -----------------------------------------------------
BRAND_DARK = (0,   0,   0)     # Solid Black
BRAND_BLUE = (60,  60,  60)    # Dark Grey for accents instead of Blue
ROW_ODD    = (245, 245, 245)   # Light Grey
ROW_EVEN   = (255, 255, 255)   # White
MUTED      = (100, 100, 100)   # Grey


def sanitize(text: str) -> str:
    """Ensure string is Latin-1 safe for fpdf2 default encoding."""
    return str(text).encode("latin-1", errors="replace").decode("latin-1")


class WorkVisionPDF(FPDF):
    """FPDF subclass that auto-adds the WorkVision branding on every page."""

    def __init__(self, title: str = "Report", subtitle: str = ""):
        super().__init__()
        self.report_title    = title
        self.report_subtitle = subtitle
        self.set_auto_page_break(auto=True, margin=20)
        self.add_page()

    def header(self):
        """Top header: logo + 'WorkVision' name + thin divider line."""
        logo_icon_path = os.path.join(BACKEND_DIR, "static", "logo_icon.png")
        logo_ok = os.path.exists(logo_icon_path)

        if logo_ok:
            self.image(logo_icon_path, x=12, y=8, w=12) # Square icon

        self.set_xy(27, 10)
        self.set_font("Helvetica", "B", 14)
        self.set_text_color(*BRAND_BLUE)
        self.cell(50, 8, "WorkVision", new_x=XPos.LMARGIN, new_y=YPos.NEXT)

        self.set_xy(100, 10)
        self.set_font("Helvetica", "B", 11)
        self.set_text_color(*BRAND_DARK)
        self.cell(95, 5, sanitize(self.report_title), align="R", new_x=XPos.LMARGIN, new_y=YPos.NEXT)

        if self.report_subtitle:
            self.set_xy(100, 16)
            self.set_font("Helvetica", "", 8)
            self.set_text_color(*MUTED)
            self.cell(95, 4, sanitize(self.report_subtitle), align="R", new_x=XPos.LMARGIN, new_y=YPos.NEXT)

        self.set_draw_color(150, 150, 150)
        self.set_line_width(0.3)
        self.line(12, 28, 200, 28)
        self.ln(6)

    def footer(self):
        """Page number at bottom (watermark removed per user request)."""
        # Removed the generated faint version of the logo as the watermark
        # if os.path.exists(LOGO_FAINT_PATH):
        #     self.image(
        #         LOGO_FAINT_PATH,
        #         x=(210 - 80) / 2,
        #         y=(297 - 80) / 2,
        #         w=80,
        #         keep_aspect_ratio=True,
        #     )

        # Page number
        self.set_y(-14)
        self.set_font("Helvetica", "I", 8)
        self.set_text_color(*MUTED)
        self.cell(0, 8, f"Generated by WorkVision  |  Page {self.page_no()}", align="C")

    def section_heading(self, text: str):
        self.set_font("Helvetica", "B", 12)
        self.set_text_color(*BRAND_BLUE)
        self.cell(0, 8, sanitize(text), new_x=XPos.LMARGIN, new_y=YPos.NEXT)
        self.set_draw_color(*BRAND_BLUE)
        self.set_line_width(0.3)
        self.line(self.l_margin, self.get_y(), self.l_margin + 60, self.get_y())
        self.ln(3)

    def info_row(self, label: str, value: str):
        self.set_font("Helvetica", "B", 9)
        self.set_text_color(*BRAND_DARK)
        self.cell(55, 6, sanitize(label) + ":", new_x=XPos.RIGHT, new_y=YPos.LAST)
        self.set_font("Helvetica", "", 9)
        self.cell(0, 6, sanitize(str(value)), new_x=XPos.LMARGIN, new_y=YPos.NEXT)

    def table_header(self, cols: list):
        self.set_fill_color(*BRAND_BLUE)
        self.set_text_color(255, 255, 255)
        self.set_font("Helvetica", "B", 8)
        for label, w in cols:
            self.cell(w, 7, sanitize(str(label)), border=0, fill=True, align="C")
        self.ln()

    def table_row(self, values: list, widths: list, row_idx: int = 0):
        fill_rgb = ROW_ODD if row_idx % 2 == 0 else ROW_EVEN
        self.set_fill_color(*fill_rgb)
        self.set_text_color(*BRAND_DARK)
        self.set_font("Helvetica", "", 8)
        for val, w in zip(values, widths):
            self.cell(w, 6, sanitize(str(val)), border=0, fill=True, align="C")
        self.ln()


# -- Public generator functions ----------------------------------------------

def ensure_logo():
    """Copy logo from public/ into backend/static/, crop it to just the W icon, and generate faint B&W watermark."""
    project_root = os.path.dirname(BACKEND_DIR)
    src = os.path.join(project_root, "public", "logo.png")
    os.makedirs(os.path.dirname(LOGO_PATH), exist_ok=True)
    logo_icon_path = os.path.join(os.path.dirname(LOGO_PATH), "logo_icon.png")

    if os.path.exists(src):
        import shutil
        shutil.copy2(src, LOGO_PATH)
        
        # Crop the logo to a square (assumes the icon is on the far left) and generate faint B&W watermark
        try:
            from PIL import Image, ImageEnhance
            with Image.open(LOGO_PATH) as img:
                img = img.convert("RGBA")
                # Crop to height x height square on the left to get just the W box
                width, height = img.size
                if width > height:
                    # It's a horizontal logo, crop the left square
                    img = img.crop((0, 0, height, height))
                
                # Save the cropped normal icon for the header
                if not os.path.exists(logo_icon_path):
                    img.save(logo_icon_path, "PNG")

                # Generate faint black & white version for the watermark
                if not os.path.exists(LOGO_FAINT_PATH):
                    # Convert to grayscale ("L"), then back to RGBA to keep alpha channel
                    bw_img = img.convert("LA").convert("RGBA")
                    # Make it highly transparent (10% opacity)
                    alpha = bw_img.split()[3]
                    alpha = ImageEnhance.Brightness(alpha).enhance(0.10)
                    bw_img.putalpha(alpha)
                    bw_img.save(LOGO_FAINT_PATH, "PNG")
        except ImportError:
            print("Warning: Pillow not installed, cannot generate logo icon or faint watermark.")
            if not os.path.exists(logo_icon_path):
                shutil.copy2(src, logo_icon_path)
            if not os.path.exists(LOGO_FAINT_PATH):
                shutil.copy2(src, LOGO_FAINT_PATH)


def _generate_trend_chart(trend_data: list) -> io.BytesIO:
    """Draws a Matplotlib line chart for Tasks Completed & Hours Worked."""
    fig, ax1 = plt.subplots(figsize=(8, 4))
    fig.patch.set_facecolor('white')
    
    # Sort data oldest to newest if needed (assuming already sorted sequentially)
    dates = [d.get("date", "") for d in trend_data]
    tasks = [d.get("tasksCompleted", 0) for d in trend_data]
    hours = [d.get("hoursWorked", 0) for d in trend_data]

    # Plot Tasks (Left Axis)
    color1 = '#6366f1'  # Indigio
    ax1.set_xlabel('Date (Last 30 Days)', fontsize=9, color='black')
    ax1.set_ylabel('Tasks Completed', color=color1, fontsize=9)
    plot1 = ax1.plot(dates, tasks, color=color1, marker='o', markersize=4, label='Tasks Completed')
    ax1.tick_params(axis='y', labelcolor=color1, labelsize=8)
    
    # Reduce X-axis density
    import matplotlib.ticker as ticker
    ax1.xaxis.set_major_locator(ticker.MaxNLocator(nbins=6))
    ax1.tick_params(axis='x', labelsize=8)
    
    # Plot Hours (Right Axis)
    ax2 = ax1.twinx()
    color2 = '#10b981'  # Emerald
    ax2.set_ylabel('Est. Hours Worked', color=color2, fontsize=9)
    plot2 = ax2.plot(dates, hours, color=color2, marker='s', markersize=4, label='Est. Hours')
    ax2.tick_params(axis='y', labelcolor=color2, labelsize=8)

    # Legends
    lns = plot1 + plot2
    labs = [l.get_label() for l in lns]
    ax1.legend(lns, labs, loc='upper left', fontsize=8, frameon=False)

    plt.grid(True, axis='y', linestyle='--', alpha=0.3)
    plt.title('Tasks Completed & Hours Worked — Last 30 Days', fontsize=11, fontweight='bold', pad=15)
    
    fig.tight_layout()
    buf = io.BytesIO()
    fig.savefig(buf, format='png', dpi=150, bbox_inches='tight')
    plt.close(fig)
    buf.seek(0)
    return buf


def _generate_dept_chart(dept_data: list) -> io.BytesIO:
    """Draws a Matplotlib bar chart for Department Scores."""
    import numpy as np
    fig, ax1 = plt.subplots(figsize=(8, 4))
    fig.patch.set_facecolor('white')

    names = [d.get("name", "") for d in dept_data]
    scores = [d.get("avgScore", 0) for d in dept_data]
    employees = [d.get("employees", 0) for d in dept_data]
    
    x = np.arange(len(names))
    width = 0.35

    color_score = '#10b981'
    color_emp = '#6366f1'

    rects1 = ax1.bar(x - width/2, scores, width, label='Avg Score', color=color_score)
    
    ax2 = ax1.twinx()
    rects2 = ax2.bar(x + width/2, employees, width, label='Employees', color=color_emp)

    ax1.set_ylabel('Average Score', color=color_score, fontsize=9)
    ax1.tick_params(axis='y', labelcolor=color_score, labelsize=8)
    ax1.set_ylim(0, 100)

    ax2.set_ylabel('Total Employees', color=color_emp, fontsize=9)
    ax2.tick_params(axis='y', labelcolor=color_emp, labelsize=8)
    # Ensure ax2 scales slightly above max employees
    max_e = max(employees) if employees else 10
    ax2.set_ylim(0, max_e * 1.5)

    ax1.set_xticks(x)
    ax1.set_xticklabels(names, rotation=15, ha="right", fontsize=8)

    # Custom legend
    ax1.legend(handles=[rects1, rects2], loc='upper right', fontsize=8, frameon=False)

    plt.title('Department Performance Overview', fontsize=11, fontweight='bold', pad=15)
    plt.grid(True, axis='y', linestyle='--', alpha=0.3)

    fig.tight_layout()
    buf = io.BytesIO()
    fig.savefig(buf, format='png', dpi=150, bbox_inches='tight')
    plt.close(fig)
    buf.seek(0)
    return buf


def generate_team_performance_pdf(employees: list, dept_name=None, trend_data: list=None, dept_stats: list=None) -> bytes:
    """
    Full team performance PDF with company branding + per-employee detailed data.
    Columns: Name | Email | Score | Category | Tasks Done | Tasks Pending | Deadline Adh. | Feedback
    """
    ensure_logo()
    now      = datetime.datetime.now().strftime("%d %B %Y, %H:%M")
    subtitle = f"Dept: {dept_name}" if dept_name else "All Departments"

    pdf = WorkVisionPDF(
        title="Team Performance Report",
        subtitle=f"{subtitle}  |  {now}",
    )

    # ── Company header block ──────────────────────────────────────────────────
    pdf.set_font("Helvetica", "B", 18)
    pdf.set_text_color(*BRAND_DARK)
    pdf.cell(0, 10, "WorkVision", align="C", new_x=XPos.LMARGIN, new_y=YPos.NEXT)

    pdf.set_font("Helvetica", "", 11)
    pdf.set_text_color(*MUTED)
    pdf.cell(0, 6, "AI-Based Employee Performance & Productivity Analysis System", align="C", new_x=XPos.LMARGIN, new_y=YPos.NEXT)
    pdf.ln(4)

    # Horizontal divider
    pdf.set_draw_color(180, 180, 180)
    pdf.set_line_width(0.4)
    pdf.line(pdf.l_margin, pdf.get_y(), 200, pdf.get_y())
    pdf.ln(6)

    # ── Summary Section ───────────────────────────────────────────────────────
    pdf.section_heading("Report Summary")
    total     = len(employees)
    avg_score = round(sum(e.get("latest_score", 0) for e in employees) / total, 1) if total else 0
    top_count = sum(1 for e in employees if e.get("status") in ("Exceptional", "High Performer"))
    low_count = sum(1 for e in employees if e.get("status") == "Needs Improvement")

    pdf.info_row("Company",           "WorkVision Analytics")
    pdf.info_row("Department",        dept_name or "All Departments")
    pdf.info_row("Total Employees",   str(total))
    pdf.info_row("Team Average Score", f"{avg_score} / 100")
    pdf.info_row("Top Performers",    f"{top_count}  (Exceptional + High Performer)")
    pdf.info_row("Need Attention",    f"{low_count}  (Needs Improvement)")
    pdf.info_row("Generated On",      now)
    pdf.ln(6)

    # ── Performance Detail Table ───────────────────────────────────────────  
    pdf.section_heading("Employee Performance Details")

    # Table columns: define widths to fit 190mm usable width
    cols = [
        ("Name",         38),
        ("Email",        45),
        ("Score",        15),
        ("Category",     28),
        ("Tasks Done",   18),
        ("Pending",      15),
        ("Adh.%",        14),
        ("Feedback",     17),
    ]
    widths = [c[1] for c in cols]
    pdf.table_header(cols)

    for i, emp in enumerate(employees):
        score     = emp.get("latest_score", 0)
        tasks_d   = emp.get("tasks_completed", 0)
        tasks_p   = emp.get("tasks_pending", 0)
        adh       = emp.get("deadline_adherence", 0)
        fb        = emp.get("feedback_score", 0)

        vals = [
            emp.get("name", "-"),
            emp.get("email", "-"),
            f"{score:.1f}",
            emp.get("status", "-"),
            str(tasks_d),
            str(tasks_p),
            f"{adh:.0f}%",
            f"{fb:.1f}" if fb else "N/A",
        ]
        pdf.table_row(vals, widths, i)

    pdf.ln(8)

    # ── Category Legend ───────────────────────────────────────────────────────
    pdf.set_font("Helvetica", "I", 8)
    pdf.set_text_color(*MUTED)
    pdf.multi_cell(0, 5,
        "Category Scale: Exceptional (>=85)  |  High Performer (>=70)  |  Average (>=55)  |  Developing (>=40)  |  Needs Improvement (<40)\n"
        "Adh.% = Deadline Adherence  |  Feedback = Manager Feedback Score (0-10)",
        align="L"
    )

    return bytes(pdf.output())



def generate_work_log_pdf(employee_name: str, department: str, logs: list) -> bytes:
    """Individual employee work log PDF."""
    ensure_logo()
    now = datetime.datetime.now().strftime("%d %B %Y, %H:%M")

    pdf = WorkVisionPDF(
        title="Work Log Report",
        subtitle=f"{employee_name}  |  {now}",
    )

    # Employee info
    pdf.section_heading("Employee Information")
    pdf.info_row("Name",         employee_name)
    pdf.info_row("Department",   department)
    pdf.info_row("Total Logs",   str(len(logs)))
    pdf.info_row("Generated On", now)
    pdf.ln(4)

    # Summary metrics
    total_hours   = sum(l.get("hours_worked", 0) for l in logs)
    total_tasks   = sum(l.get("tasks_assigned", 0) for l in logs)
    done_tasks    = sum(l.get("tasks_completed", 0) for l in logs)
    avg_adherence = round(sum(l.get("deadline_adherence", 0) for l in logs) / len(logs), 1) if logs else 0

    pdf.section_heading("Overall Summary")
    pdf.info_row("Total Hours Worked",     f"{total_hours:.1f} hrs")
    pdf.info_row("Total Tasks Assigned",   str(total_tasks))
    pdf.info_row("Total Tasks Completed",  str(done_tasks))
    pdf.info_row("Avg Deadline Adherence", f"{avg_adherence}%")
    pdf.ln(4)

    # Log entries table
    pdf.section_heading("Work Log Entries")
    cols   = [("Date", 30), ("Assigned", 25), ("Done", 25), ("Hours", 20), ("Adherence%", 28), ("Delays", 18), ("Notes", 44)]
    widths = [c[1] for c in cols]
    pdf.table_header(cols)

    for i, log in enumerate(logs):
        raw = log.get("date", "")
        if hasattr(raw, "strftime"):
            date_str = raw.strftime("%Y-%m-%d")
        elif isinstance(raw, str):
            date_str = raw[:10]
        else:
            date_str = str(raw)[:10]

        notes = str(log.get("notes", "")).strip()[:30]
        vals  = [
            date_str,
            str(log.get("tasks_assigned", 0)),
            str(log.get("tasks_completed", 0)),
            f"{log.get('hours_worked', 0):.1f}",
            f"{log.get('deadline_adherence', 0):.0f}%",
            str(log.get("delay_count", 0)),
            notes or "-",
        ]
        pdf.table_row(vals, widths, i)

    return bytes(pdf.output())


def generate_proof_of_work_pdf(employee: dict, log: dict, completed_tasks: list) -> bytes:
    """Branded 'Proof of Work' PDF certificate for an employee."""
    ensure_logo()
    log_date_raw = log.get("date", datetime.datetime.utcnow())
    if hasattr(log_date_raw, "strftime"):
        log_date = log_date_raw.strftime("%d %B %Y")
    else:
        log_date = str(log_date_raw)[:10]

    now = datetime.datetime.utcnow().strftime("%d %B %Y, %H:%M UTC")

    pdf = WorkVisionPDF(title="Proof of Work Certificate", subtitle=f"Date: {log_date}")

    # Section: Employee Details
    pdf.section_heading("Employee Details")
    pdf.info_row("Name",       employee.get("name", "N/A"))
    pdf.info_row("Email",      employee.get("email", "N/A"))
    pdf.info_row("Department", employee.get("department", "N/A"))
    pdf.info_row("Log Date",   log_date)
    pdf.ln(5)

    # Section: Log Summary
    pdf.section_heading("Work Log Summary")
    pdf.info_row("Verified Tasks Assigned",  str(log.get("tasks_assigned", 0)))
    pdf.info_row("Verified Tasks Completed", str(log.get("tasks_completed", 0)))
    pdf.info_row("Hours Worked",             f"{log.get('hours_worked', 0):.1f} hrs")
    pdf.info_row("Deadline Adherence",       f"{log.get('deadline_adherence', 100):.0f}%")
    pdf.info_row("Delay Count",              str(log.get("delay_count", 0)))
    if log.get("notes"):
        pdf.ln(2)
        pdf.info_row("Notes", log.get("notes").strip()[:100])
    pdf.ln(5)

    # Section: Task Detail Table
    pdf.section_heading("Completed Tasks (Manager-Verified Evidence)")
    if completed_tasks:
        cols = [("Task Title", 100), ("Submitted At", 40), ("Hours", 20)]
        widths = [c[1] for c in cols]
        pdf.table_header(cols)
        
        for i, t in enumerate(completed_tasks):
            title = str(t.get('title', 'Untitled Task')).strip()[:60]
            sub = t.get('submitted_at')
            sub_str = sub.strftime("%Y-%m-%d %H:%M") if hasattr(sub, "strftime") else str(sub)[:16]
            hrs = f"{t.get('hours_spent', 0):.1f}"
            pdf.table_row([title, sub_str, hrs], widths, i)
    else:
        pdf.set_font("Helvetica", "I", 9)
        pdf.set_text_color(*MUTED)
        pdf.cell(0, 6, "No manager-verified tasks logged in this period.", new_x=XPos.LMARGIN, new_y=YPos.NEXT)

    pdf.ln(10)
    pdf.set_font("Helvetica", "BI", 8)
    pdf.set_text_color(*BRAND_BLUE)
    pdf.cell(0, 6, "This certificate is automatically generated and structurally verified by WorkVision.", align="C")

    return bytes(pdf.output())

